version: '3'

services:
  beerservice:
    build: ./beerService
    networks:
      - proxynet
    ports:
      - 8080:8080
    depends_on:
      - db
  playlistservice:
    build: ./playlistService
    networks:
      - proxynet
    ports:
      - 8081:8081
    depends_on:
      - beerservice
  webapi:
    build: ./webApi
    networks:
      - proxynet
    ports:
      - 8082:8082
    depends_on:
      - beerservice
      - playlistservice
volumes:
  data-db:
networks:
  proxynet:
    driver: bridge
